### ISSUE TITLE
Add -7 as alias for m7

### ISSUE THREAD

**Issue by mrjacobbloom** [nolanlawson/chord-magic#2]
I'm writing a lead-sheet editor, and I'm running into an issue where -7 is parsed incorrectly. For example:
```
// Expected:
chordMagic.parse('A-7') // {root: "A", quality: "Minor", extended: "Minor7"}
// Actual:
chordMagic.parse('A-7') // {root: "A", quality: "Major"}
```
To my knowledge -7 for Minor7 is a fairly common notation. While I can change the input to compensate, it'd be nice if this module did that natively.

**Comment by nolanlawson** [comment]
PRs welcome, I wasn't aware of this notation. :)

**Comment by mrjacobbloom** [comment]
Thanks!
