### ISSUE TITLE
Allow flats to be expressed as sharps

### ISSUE THREAD

**Issue by justinlawrence** [nolanlawson/chord-magic#3]
We were keen to use this library, but could not have a D/F# chord expressed as D/Gb.

Might be worth adding as another language? Perhaps "English-Sharp".

**Comment by nolanlawson** [comment]
duplicate of #1, yes there should be more options to choose sharps vs flats etc

**Comment by nolanlawson** [comment]
Custom note namings are now supported and published in v2.1.0. Thanks for the suggestion!

**Comment by justinlawrence** [comment]
Thanks Nolan!!
